# Automatically generated by configure - do not modify
TARGET_PPC64=y
TARGET_NAME=ppc64
TARGET_BASE_ARCH=ppc
TARGET_WORDS_BIGENDIAN=y
CONFIG_SOFTMMU=y
LDFLAGS+=
QEMU_CFLAGS+=
QEMU_CFLAGS+=-include ppc64.h
