# Automatically generated by configure - do not modify
TARGET_PPCEMB=y
TARGET_NAME=ppcemb
TARGET_BASE_ARCH=ppc
TARGET_WORDS_BIGENDIAN=y
CONFIG_SOFTMMU=y
LDFLAGS+=
QEMU_CFLAGS+=
QEMU_CFLAGS+=-include ppcemb.h
